# https://canonical-charm-refresh.readthedocs-hosted.com/latest/refresh-versions-toml/

charm_major = 0
workload = "8.0.42"

[snap]
name = "charmed-mysql"

[snap.revisions]
# amd64
x86_64 = "151"
# arm64
aarch64 = "153"
# s390x
s390x = "152"
